export const bossesArray = [
  {
    mobName: 'Архон',
    shortName: 'Арх',
    mobType: 'Босс',
    image: 'arch.avif',
    respawnText:
      'В месте мрачном и пустынном сплетает свои сети отец злодейства.',
  },
  {
    mobName: 'Баксбакуалануксивайе',
    shortName: 'Бакс',
    mobType: 'Босс',
    image: 'baks.avif',
    respawnText:
      'Грохот и рычание сотрясают вековечные льды и снега. Похоже, там проснулся кто-то очень голодный?',
  },
  {
    mobName: 'Воко',
    shortName: 'Воко',
    mobType: 'Босс',
    image: 'voko.avif',
    respawnText:
      'Заиндевевшие клешни царапают старый лед... Обледенелый панцирь обдирает своды промерзлой пещеры... Царь северных гор жаждет новых душ!',
  },
  {
    mobName: 'Гигантская Тортолла',
    shortName: 'ГТ',
    mobType: 'Босс',
    image: 'gt.avif',
    respawnText: 'Древнее зло пробудилось, но лишь стражник Алнора видит его.',
  },
  {
    mobName: 'Денгур Кровавый топор',
    shortName: 'Ден',
    mobType: 'Босс',
    image: 'den.avif',
    respawnText:
      'Над морозным краем, покрытым снегом, разлетается звон стальных лезвий. Кто-то яростно и громко бьет двумя топорами, сотрясая землю.',
  },
  {
    mobName: 'Деструктор',
    shortName: 'Дестр',
    mobType: 'Босс',
    image: 'destr.avif',
    respawnText: 'Пустыня осенена знаком ворона у склонов пирамиды.',
  },
  {
    mobName: 'Древний Энт',
    shortName: 'Энт',
    mobType: 'Босс',
    image: 'ent.avif',
    respawnText: 'Древний лес наступает на Литанский замок.',
  },
  {
    mobName: 'Зверомор',
    shortName: 'Звер',
    mobType: 'Босс',
    image: 'zver.avif',
    respawnText: 'Грибы подняли восстание, и неспроста.',
  },
  {
    mobName: 'Королева Крыс',
    shortName: 'КК',
    mobType: 'Босс',
    image: 'kk.avif',
    respawnText:
      'У Борга Харригана снова болит голова... Удивительно, почему же?',
  },
  {
    mobName: 'Пружинка',
    shortName: 'Пружа',
    mobType: 'Босс',
    image: 'spring.avif',
    respawnText:
      'Повелитель Пружинок изволил проснуться у завода мрачных коробок и требует богатых даров.',
  },
  {
    mobName: 'Тёмный Шаман',
    shortName: 'Шаман',
    mobType: 'Босс',
    image: 'shaman.avif',
    respawnText: 'Тыква старины Тью под угрозой!',
  },
  {
    mobName: 'Хьюго',
    shortName: 'Хьюго',
    mobType: 'Босс',
    image: 'hugo.avif',
    respawnText: 'Молоторукий в землях севера сулит унижения слабым.',
  },
  {
    mobName: 'Эдвард',
    shortName: 'Эд',
    mobType: 'Босс',
    image: 'ed.avif',
    respawnText: 'Снова будет много лезвий и бритвенной пены.',
  },
  {
    mobName: 'Дуан Безжалостный',
    shortName: 'Дуан',
    mobType: 'Босс',
    image: 'duan.avif',
    respawnText: 'Текст респауна',
  },
];

export const elitesArray = [
  {
    mobName: 'Альфа Самец',
    shortName: 'Альфа',
    mobType: 'Элитка',
    image: 'alfa.avif',
  },
  {
    mobName: 'Богатый Упырь',
    shortName: 'БУ',
    mobType: 'Элитка',
    image: 'bu.avif',
  },
  {
    mobName: 'Жужелица Тёмная',
    shortName: 'Жужелица',
    mobType: 'Элитка',
    image: 'jt.avif',
  },
  {
    mobName: 'Золотой Таракан',
    shortName: 'ЗТ',
    mobType: 'Элитка',
    image: 'zt.avif',
  },
  {
    mobName: 'Кабан Вожак',
    shortName: 'Кабан',
    mobType: 'Элитка',
    image: 'kaban.avif',
  },
  {
    mobName: 'Королева Термитов',
    shortName: 'КТ',
    mobType: 'Элитка',
    image: 'kt.avif',
  },
  {
    mobName: 'Королевская Терния',
    shortName: 'Терния',
    mobType: 'Элитка',
    image: 'kortor.avif',
  },
  {
    mobName: 'Королевский Паук',
    shortName: 'Королевский Паук',
    mobType: 'Элитка',
    image: 'korpauk.avif',
  },
  {
    mobName: 'Лякуша',
    shortName: 'Лякуша',
    mobType: 'Элитка',
    image: 'lyakusha.avif',
  },
  {
    mobName: 'Мега Ирекс',
    shortName: 'Мега',
    mobType: 'Элитка',
    image: 'mega.avif',
  },
  {
    mobName: 'Пещерный Волк',
    shortName: 'Пещерный Волк',
    mobType: 'Элитка',
    image: 'wolf.avif',
  },
  {
    mobName: 'Пламярык',
    shortName: 'Пламик',
    mobType: 'Элитка',
    image: 'plamya.avif',
  },
  {
    mobName: 'Превосходный пожиратель моземия',
    shortName: 'Пожик(О)',
    mobType: 'Элитка',
    image: 'pojikO.avif',
  },
  {
    mobName: 'Превосходный пожиратель элениума',
    shortName: 'Пожик(С)',
    mobType: 'Элитка',
    image: 'pojikC.avif',
  },
  {
    mobName: 'Самка Жужа',
    shortName: 'Самка',
    mobType: 'Элитка',
    image: 'samka.avif',
  },
  {
    mobName: 'Слепоглаз',
    shortName: 'Слепоглаз',
    mobType: 'Элитка',
    image: 'slep.avif',
  },
  {
    mobName: 'Советник Остина',
    shortName: 'Остин',
    mobType: 'Элитка',
    image: 'ostin.avif',
  },
  {
    mobName: 'Тринадцатый Крыс',
    shortName: '13 Крыс',
    mobType: 'Элитка',
    image: 'hanya.avif',
  },
  {
    mobName: 'Тёмный Оракул',
    shortName: 'Оракул',
    mobType: 'Элитка',
    image: 'oracul.avif',
  },
  {
    mobName: 'Фараон',
    shortName: 'Фара',
    mobType: 'Элитка',
    image: 'pharaon.avif',
  },
  {
    mobName: 'Хозяин',
    shortName: 'Хозя',
    mobType: 'Элитка',
    image: 'hozya.avif',
  },
  {
    mobName: 'Чёрная Вдова',
    shortName: 'Чёрная Вдова',
    mobType: 'Элитка',
    image: 'bw.avif',
  },
];
