name: SSH Action

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PASS: ${{ secrets.SSH_PASS }}
        DATABASE_USER_TEST: ${{ secrets.DATABASE_USER_TEST }}
        DATABASE_PASSWORD_TEST: ${{ secrets.DATABASE_PASSWORD_TEST }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        GRANAS_TOKEN: ${{ secrets.GRANAS_TOKEN }}
        ENIGMA_TOKEN: ${{ secrets.ENIGMA_TOKEN }}
        LOGRUS_TOKEN: ${{ secrets.LOGRUS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          password: ${{ secrets.SSH_PASS }}
          port: 22
          script: |
            cd TimerRQ
            git pull
            cd backend
            if [ -f .env ]; then rm .env; fi
            echo "DATABASE_USER_TEST=${{ secrets.DATABASE_USER_TEST }}" >> .env
            echo "DATABASE_PASSWORD_TEST=${{ secrets.DATABASE_PASSWORD_TEST }}" >> .env
            echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env
            echo "GRANAS_TOKEN=${{ secrets.GRANAS_TOKEN }}" >> .env
            echo "ENIGMA_TOKEN=${{ secrets.ENIGMA_TOKEN }}" >> .env
            echo "LOGRUS_TOKEN=${{ secrets.LOGRUS_TOKEN }}" >> .env
            npm install
            npm run build
            cd dist
            pm2 restart main.js ecosystem.config.js
            sudo service nginx restart

            
