name: SSH Action

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_PASS: ${{ secrets.SSH_PASS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          password: ${{ secrets.ROOT_PASSWORD }}
          port: 22
          script: |
            cd TimerRQ
            git pull
            npm install
            npm run build
            cd dist
            pm2 restart main.js
            sudo service nginx restart

            
